pipelines:
  build-and-deploy:
    group: defaultGroup
    label_template: ${COUNT}
    materials:
      mygit:
        git: https://github.com/shubham-kanodia/AkkaHTTP.git
        branch: master
    stages:
      - build:
          fetch_materials: true
          clean_workspace: false
          jobs:
            build:
              tasks:
               - exec:
                   command: sbt
                   arguments:
                      - clean
                      - compile
                      - test
      - publish:
          fetch_materials: true
          clean_workspace: false
          jobs:
            publish:
              environment_variables:
                DOCKERHUB_USERNAME: shubhamkanodia
              secure_variables:
                DOCKERHUB_PASSWORD: "AES:HJWSOnCVGxHyLGC2DM1DjA==:W2PcdMdE6aBwCDKcNnamrFHLP+UHCC9ZdMDxabngPhY="
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
                - exec:
                    command: sbt
                    arguments:
                      - docker:publish
                    working_directory: AkkaHTTP
      - deploy:
          clean_workspace: false
          jobs:
            deploy:
              tasks:
                - exec:
                  command: sh
                  arguments:
                    - -c
                    - kubectl apply -f deployment.yaml
                  working_directory: AkkaHTTP/K8
                - exec:
                  command: sh
                  arguments:
                    - -c
                    - kubectl apply -f nodeport-service.yaml 
                  working_directory: AkkaHTTP/K8
