apiVersion: v1
kind: Pod
metadata:
  name: greeting-api
  labels:
    app: greeting
spec:
  containers:
  - name: greeting-api
    image: shubhamkanodia/greetingapi:7
    ports:
    - containerPort: 8080